package ptm.home.entity;
// Generated Jun 7, 2020 7:43:22 AM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Designation generated by hbm2java
 */
@Entity
@Table(name = "designation", catalog = "ptm_dev", uniqueConstraints = @UniqueConstraint(columnNames = { "role_id",
		"department_id" }))
public class Designation implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department_id", nullable = false)
	private Department department;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedBy")
	private Employee updatedBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdBy", nullable = false)
	private Employee createdBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	private Role role;

	@Column(name = "role_name", nullable = false, length = 50)
	private String roleName;

	@Column(name = "department_name", nullable = false, length = 50)
	private String departmentName;

	@Column(name = "designationName", length = 50)
	private String designationName;

	@Column(name = "hierarchy", nullable = false)
	private int hierarchy;

	@Column(name = "description", nullable = false, length = 50)
	private String description;

	@Column(name = "enabled", nullable = false, length = 5)
	private String enabled;

	@Column(name = "deleted", nullable = false, length = 5)
	private String deleted;

	@Column(name = "createdOn", nullable = false, length = 26)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "updatedOn", length = 26)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designation")
	private Set<UserRole> userRoles = new HashSet<UserRole>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designation")
	private Set<UserRole> userRoles_1 = new HashSet<UserRole>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designation")
	private Set<Employee> employees = new HashSet<Employee>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designation")
	private Set<Employee> employees_1 = new HashSet<Employee>(0);

	public Designation() {
	}

	public Designation(Department department, Employee createdBy, Role role, String roleName, String departmentName,
			int hierarchy, String description, String enabled, String deleted, LocalDateTime createdOn) {
		this.department = department;
		this.createdBy = createdBy;
		this.role = role;
		this.roleName = roleName;
		this.departmentName = departmentName;
		this.hierarchy = hierarchy;
		this.description = description;
		this.enabled = enabled;
		this.deleted = deleted;
		this.createdOn = createdOn;
	}

	public Designation(Department department, Employee updatedBy, Employee createdBy, Role role, String roleName,
			String departmentName, String designationName, int hierarchy, String description, String enabled,
			String deleted, LocalDateTime createdOn, LocalDateTime updatedOn, Set<UserRole> userRoles,
			Set<UserRole> userRoles_1, Set<Employee> employees, Set<Employee> employees_1) {
		this.department = department;
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.role = role;
		this.roleName = roleName;
		this.departmentName = departmentName;
		this.designationName = designationName;
		this.hierarchy = hierarchy;
		this.description = description;
		this.enabled = enabled;
		this.deleted = deleted;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.userRoles = userRoles;
		this.userRoles_1 = userRoles_1;
		this.employees = employees;
		this.employees_1 = employees_1;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Employee getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Employee updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Employee getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getDesignationName() {
		return this.designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	public int getHierarchy() {
		return this.hierarchy;
	}

	public void setHierarchy(int hierarchy) {
		this.hierarchy = hierarchy;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Set<UserRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<UserRole> userRoles) {
		this.userRoles = userRoles;
	}

	public Set<UserRole> getUserRoles_1() {
		return this.userRoles_1;
	}

	public void setUserRoles_1(Set<UserRole> userRoles_1) {
		this.userRoles_1 = userRoles_1;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	public Set<Employee> getEmployees_1() {
		return this.employees_1;
	}

	public void setEmployees_1(Set<Employee> employees_1) {
		this.employees_1 = employees_1;
	}

}
