package ptm.home.entity;
// Generated Jun 7, 2020 7:43:22 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * IndiaState generated by hbm2java
 */
@Entity
@Table(name = "india_state", catalog = "ptm_dev")
public class IndiaState implements java.io.Serializable {

	@Id

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@Column(name = "name", nullable = false, length = 50)
	private String name;

	@Column(name = "capital", length = 50)
	private String capital;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indiaState")
	private Set<Employee> employees = new HashSet<Employee>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indiaState")
	private Set<Employee> employees_1 = new HashSet<Employee>(0);

	public IndiaState() {
	}

	public IndiaState(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public IndiaState(int id, String name, String capital, Set<Employee> employees, Set<Employee> employees_1) {
		this.id = id;
		this.name = name;
		this.capital = capital;
		this.employees = employees;
		this.employees_1 = employees_1;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	public Set<Employee> getEmployees_1() {
		return this.employees_1;
	}

	public void setEmployees_1(Set<Employee> employees_1) {
		this.employees_1 = employees_1;
	}

}
