package ptm.home.entity;
// Generated Jun 7, 2020 7:43:22 AM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "ptm_dev", uniqueConstraints = { @UniqueConstraint(columnNames = "menuKey"),
		@UniqueConstraint(columnNames = "menuUrl") })
public class Menu implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedBy")
	private Employee updatedBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdBy", nullable = false)
	private Employee createdBy;

	@Column(name = "menuKey", unique = true, nullable = false, length = 50)
	private String menuKey;

	@Column(name = "menuName", nullable = false, length = 50)
	private String menuName;

	@Column(name = "menuUrl", unique = true, nullable = false, length = 50)
	private String menuUrl;

	@Column(name = "menuType", nullable = false, length = 50)
	private String menuType;

	@Column(name = "serialNo", nullable = false)
	private int serialNo;

	@Column(name = "enabled", nullable = false, length = 5)
	private String enabled;

	@Column(name = "deleted", nullable = false, length = 5)
	private String deleted;

	@Column(name = "createdOn", nullable = false, length = 26)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "updatedOn", length = 26)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	private Set<SubMenu> subMenus = new HashSet<SubMenu>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu")
	private Set<SubMenu> subMenus_1 = new HashSet<SubMenu>(0);

	public Menu() {
	}

	public Menu(Employee createdBy, String menuKey, String menuName, String menuUrl, String menuType, int serialNo,
			String enabled, String deleted, LocalDateTime createdOn) {
		this.createdBy = createdBy;
		this.menuKey = menuKey;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuType = menuType;
		this.serialNo = serialNo;
		this.enabled = enabled;
		this.deleted = deleted;
		this.createdOn = createdOn;
	}

	public Menu(Employee updatedBy, Employee createdBy, String menuKey, String menuName, String menuUrl,
			String menuType, int serialNo, String enabled, String deleted, LocalDateTime createdOn,
			LocalDateTime updatedOn, Set<SubMenu> subMenus, Set<SubMenu> subMenus_1) {
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.menuKey = menuKey;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuType = menuType;
		this.serialNo = serialNo;
		this.enabled = enabled;
		this.deleted = deleted;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.subMenus = subMenus;
		this.subMenus_1 = subMenus_1;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Employee updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Employee getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}

	public String getMenuKey() {
		return this.menuKey;
	}

	public void setMenuKey(String menuKey) {
		this.menuKey = menuKey;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuType() {
		return this.menuType;
	}

	public void setMenuType(String menuType) {
		this.menuType = menuType;
	}

	public int getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(int serialNo) {
		this.serialNo = serialNo;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

	public Set<SubMenu> getSubMenus() {
		return this.subMenus;
	}

	public void setSubMenus(Set<SubMenu> subMenus) {
		this.subMenus = subMenus;
	}

	public Set<SubMenu> getSubMenus_1() {
		return this.subMenus_1;
	}

	public void setSubMenus_1(Set<SubMenu> subMenus_1) {
		this.subMenus_1 = subMenus_1;
	}

}
