package ptm.home.entity;
// Generated Jun 7, 2020 7:43:22 AM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.time.LocalDateTime;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SubMenuDependency generated by hbm2java
 */
@Entity
@Table(name = "sub_menu_dependency", catalog = "ptm_dev")
public class SubMenuDependency implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedBy")
	private Employee updatedBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdBy", nullable = false)
	private Employee createdBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subMenu_id", nullable = false)
	private SubMenu subMenuBySubMenuId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subMenu_dependency_id", nullable = false)
	private SubMenu subMenuBySubMenuDependencyId;

	@Column(name = "t_submenu_key", nullable = false, length = 50)
	private String TSubmenuKey;

	@Column(name = "t_subMenu_dependency_key", nullable = false, length = 50)
	private String TSubMenuDependencyKey;

	@Column(name = "index", nullable = false)
	private int index;

	@Column(name = "createdOn", nullable = false, length = 26)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "updatedOn", length = 26)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	public SubMenuDependency() {
	}

	public SubMenuDependency(Employee createdBy, SubMenu subMenuBySubMenuId, SubMenu subMenuBySubMenuDependencyId,
			String TSubmenuKey, String TSubMenuDependencyKey, int index, LocalDateTime createdOn) {
		this.createdBy = createdBy;
		this.subMenuBySubMenuId = subMenuBySubMenuId;
		this.subMenuBySubMenuDependencyId = subMenuBySubMenuDependencyId;
		this.TSubmenuKey = TSubmenuKey;
		this.TSubMenuDependencyKey = TSubMenuDependencyKey;
		this.index = index;
		this.createdOn = createdOn;
	}

	public SubMenuDependency(Employee updatedBy, Employee createdBy, SubMenu subMenuBySubMenuId,
			SubMenu subMenuBySubMenuDependencyId, String TSubmenuKey, String TSubMenuDependencyKey, int index,
			LocalDateTime createdOn, LocalDateTime updatedOn) {
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.subMenuBySubMenuId = subMenuBySubMenuId;
		this.subMenuBySubMenuDependencyId = subMenuBySubMenuDependencyId;
		this.TSubmenuKey = TSubmenuKey;
		this.TSubMenuDependencyKey = TSubMenuDependencyKey;
		this.index = index;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Employee getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Employee updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Employee getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}

	public SubMenu getSubMenuBySubMenuId() {
		return this.subMenuBySubMenuId;
	}

	public void setSubMenuBySubMenuId(SubMenu subMenuBySubMenuId) {
		this.subMenuBySubMenuId = subMenuBySubMenuId;
	}

	public SubMenu getSubMenuBySubMenuDependencyId() {
		return this.subMenuBySubMenuDependencyId;
	}

	public void setSubMenuBySubMenuDependencyId(SubMenu subMenuBySubMenuDependencyId) {
		this.subMenuBySubMenuDependencyId = subMenuBySubMenuDependencyId;
	}

	public String getTSubmenuKey() {
		return this.TSubmenuKey;
	}

	public void setTSubmenuKey(String TSubmenuKey) {
		this.TSubmenuKey = TSubmenuKey;
	}

	public String getTSubMenuDependencyKey() {
		return this.TSubMenuDependencyKey;
	}

	public void setTSubMenuDependencyKey(String TSubMenuDependencyKey) {
		this.TSubMenuDependencyKey = TSubMenuDependencyKey;
	}

	public int getIndex() {
		return this.index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

}
