package ptm.home.entity;
// Generated Jun 7, 2020 7:43:22 AM by Hibernate Tools 5.2.12.Final

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import javax.persistence.*;
import java.time.LocalDateTime;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "ptm_dev", uniqueConstraints = @UniqueConstraint(columnNames = { "designation_id",
		"submenu_command_id" }))
public class UserRole implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private int id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "designation_id", nullable = false)
	private Designation designation;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "updatedBy")
	private Employee updatedBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "createdBy", nullable = false)
	private Employee createdBy;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "submenu_command_id", nullable = false)
	private SubMenu subMenu;

	@Column(name = "t_designation_name", nullable = false, length = 50)
	private String TDesignationName;

	@Column(name = "t_menu_cmd_name", nullable = false, length = 50)
	private String TMenuCmdName;

	@Column(name = "enabled", nullable = false, length = 5)
	private String enabled;

	@Column(name = "deleted", nullable = false, length = 5)
	private String deleted;

	@Column(name = "createdOn", nullable = false, length = 26)
	@CreationTimestamp
	private LocalDateTime createdOn;

	@Column(name = "updatedOn", length = 26)
	@UpdateTimestamp
	private LocalDateTime updatedOn;

	public UserRole() {
	}

	public UserRole(Designation designation, Employee createdBy, SubMenu subMenu, String TDesignationName,
			String TMenuCmdName, String enabled, String deleted, LocalDateTime createdOn) {
		this.designation = designation;
		this.createdBy = createdBy;
		this.subMenu = subMenu;
		this.TDesignationName = TDesignationName;
		this.TMenuCmdName = TMenuCmdName;
		this.enabled = enabled;
		this.deleted = deleted;
		this.createdOn = createdOn;
	}

	public UserRole(Designation designation, Employee updatedBy, Employee createdBy, SubMenu subMenu,
			String TDesignationName, String TMenuCmdName, String enabled, String deleted, LocalDateTime createdOn,
			LocalDateTime updatedOn) {
		this.designation = designation;
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.subMenu = subMenu;
		this.TDesignationName = TDesignationName;
		this.TMenuCmdName = TMenuCmdName;
		this.enabled = enabled;
		this.deleted = deleted;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Designation getDesignation() {
		return this.designation;
	}

	public void setDesignation(Designation designation) {
		this.designation = designation;
	}

	public Employee getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Employee updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Employee getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Employee createdBy) {
		this.createdBy = createdBy;
	}

	public SubMenu getSubMenu() {
		return this.subMenu;
	}

	public void setSubMenu(SubMenu subMenu) {
		this.subMenu = subMenu;
	}

	public String getTDesignationName() {
		return this.TDesignationName;
	}

	public void setTDesignationName(String TDesignationName) {
		this.TDesignationName = TDesignationName;
	}

	public String getTMenuCmdName() {
		return this.TMenuCmdName;
	}

	public void setTMenuCmdName(String TMenuCmdName) {
		this.TMenuCmdName = TMenuCmdName;
	}

	public String getEnabled() {
		return this.enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	public String getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted = deleted;
	}

	public LocalDateTime getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDateTime createdOn) {
		this.createdOn = createdOn;
	}

	public LocalDateTime getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(LocalDateTime updatedOn) {
		this.updatedOn = updatedOn;
	}

}
